# introduction to SOC
how scale invariant struction, like mass, real number that is fractal dimention of the object,
it a one way of serching fractal dimention.
from phycal phenomena to geometry, like perpolation, there is a random walk, diffusion problems in physics,
this has to do with space and time. not true that every thing heppen at the same time.

there are finantial, social technological.
a lot have to deals with orders, example of a pizza, firt in firt out, is the simplest.
we have orders, and disorder and the pizza wil go good or bad

in a bank fifo is not what we want. we want to sell at a certain price, and someone else want to buy at a certain price.
and need we need an officier to do some finantial dealer. is how a market guy work. and the market is a fractal.

more client he can match, the heppier the client are, and the more money he make.
find the best possible match, is a fractal problem.

order do not cover always, there is a precize moment in time, where the order is valid.
it's dynamics and it's not continuous.

social is the same, we have a lot of order, and we have to match them.
in the past we can chack how many letter they sent per day. even now the email is avalance effect

Avalace effect can broke the system. in the bank we see this process. like the price of the house, it can crash.
there is the Ipoteca. can appen a bankrupcy, and the bank can go down, and no longer able to pay back.
also heartquake, and the avalance effect can be a fractal. it change the equilibrium.

# SOC (self organize criticality)
a model to describe this are "called self organize critical". are not thermodynamical system.
those system are open dynamical system. the amount of matter can change in time. and the equilibrium is critical and controlled by power law.
they self organize to a such state, it's important. life is self organize.
why a system is in such condiction to make self organize?
image a table, you can accumulate little ball, sand. at a certain point it will be filled. the system is open, you can add and lose, and is also dissipating energy
there is 2 way to change matter, you, and the system it-serf, we expect statystical equilibrium.
another way is losing matter, and it's an avalance effect. you put 1 you can lose 1000000.
we need to tune control the parameter to a precize value

the system can be empty or full, and the system is critical, and the system is self organize.
it's possible to compute the size of the avalance.

the event in an avalanche process are interconected.

### heartquake and other phenomena
the heartquake is a SOC, and the avalance is the heartquake.
also fire forest


### finantial market
can total collaps of the market, a big crash. it's important to understand the model.

### charles darwin
also charles darwin observe this phenomena
mutation are random, one of individual might be better than the other, and the other will die.
every space tend to destroy the envirormant to dominat it.
bacteria made a mutation, made chianobacteria and they start producing oxigen, and they kill all the other bacteria and the envirorment.
it's not an excuse to our behavior, we are not bacteria, we can control our-self.

but bacterya show us that over an equilibrim the effect can be catastrophic.



# things can go bad :)  :(

we will simulate a rice pack
i fyou trhow a race of rice,
rice pie is a famous paper published, and it's a SOC model.


the most general case is poisson procces, or binomial process
it's use because it's easy to compute. and to understand.
p is success, and 1-p is failure.



# SOC model
we have a system, and we have a parameter, and we have a critical value, and we have a avalance effect.
the concept is by a paper in 1987 by bak, tang and wiesenfeld who use a sand pile model.
the sand pile model is a 2d model, and we have a pile of sand, and we add sand, and we have a critical value, and we have a avalance effect.

self organize critically is a concempt. it can be found in many system. in particular in 2 system:
- sand pile model
- forest fire model
- rice pile model
- earthquake model
- finantial market model
- evolution model
- brain model
- traffic model
- epidemic model

image a 2d lattice of sand and every cell is a cilinder with other sand in it and we add sand, and we have a critical value, and we have a avalance effect.

k=0,1,2,3 is stable state, and k=4 is unstable state, and k=5 is the avalance effect.
you throw sand randomly and you have a critical value, and you have a avalance effect.
there is avalance to up down and left right, and the avalance is a fractal.the avalanche can make another avalanche to the nearest neighbor.
if sand exceed the lattice the sand is lost forever and the system is open.
i,j is the lattice side.
start empty and add sand, and the sand is added randomly. or start with an avalanche and see what happen.

there is wave phenomena.
big avalanche are possible, like crash market, or big earthquake.


# simulation of send pile model

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib import colors
import random
import time

In [28]:
# define the size of the lattice
N = 100
a = np.array()
# define the number of iteration
n_iter = 10000
alfa = 0.5
beta = 1

In [33]:
# DEFINE LATTICE
fitness_landscape = np.random.randint(0, 5, size=(N, N))
print(fitness_landscape)

[[2 1 2 ... 4 4 2]
 [3 0 2 ... 3 4 4]
 [0 0 1 ... 4 3 3]
 ...
 [0 3 0 ... 3 0 4]
 [1 1 4 ... 0 1 2]
 [4 2 2 ... 4 3 1]]


In [34]:
# add sand
def add_sand(lattice, i, j):
    lattice[i, j] += 1
    return lattice

In [ ]:
# define the avalanche
def